cripto/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.urls import path

# import statistic.urls as stat_url

# urlpatterns = [
#     url('^e5c9247a98c58dda4e6749fe081fb79a/', include([
#         url('^admin/$', admin.site.urls),
#         url('^statistic/$', include('statistic.urls'), name='statistic'),
#         url('^trading/$', include('trading.urls'), name='traiding'),
#     ],
#     )),
#
#     url('^telegram/', include('test_telegram.urls', namespace='telegram')),
# ]

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('sentry-debug/', trigger_error),
    # path('e5c9247a98c58dda4e6749fe081fb79a/', admin.site.urls),
    # path('e5c9247a98c58dda4e6749fe081fb79a/statistic/', include(('statistic.urls', 'statistic'), namespace='statistic')),
    path('e5c9247a98c58dda4e6749fe081fb79a/tr/', include(('trading.urls', 'trading'), namespace='trading')),
    path('e5c9247a98c58dda4e6749fe081fb79a/st/', include(('statistic.urls', 'statistic'), namespace='statistic')),
    # url('^e5c9247a98c58dda4e6749fe081fb79a/stat/', include(('statistic.urls', 'statistic'), namespace='stat')),
    # url('^e5c9247a98c58dda4e6749fe081fb79a/stat/', include(('statistic.urls', 'statistic'), namespace='stat')),
    # url(r'^e5c9247a98c58dda4e6749fe081fb79a/stat/', include(('statistic.urls', 'statistic'), namespace='statistic')),
    # path('telegram/', include(('test_telegram.urls', 'telegram'), namespace='telegram')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/', include('jet.urls', 'jet')),
    path('e5c9247a98c58dda4e6749fe081fb79a/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # urlpatterns += [
    #     (r'^media/(?P<path>.*)$', 'django.views.static.serve',
    #      {'document_root': settings.MEDIA_ROOT}),
    #     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    #      {'document_root': settings.STATIC_ROOT}),
    #
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

statistic/urls.py
from django.urls import path

import statistic.views

urlpatterns = [

    path('main/', statistic.views.index, name='main'),
    path('main/bittrex/', statistic.views.index, {'exchange_name': 'bittrex'}, name='main-bittrex'),
    path('main/<slug:exchange_name>/<slug:market_name>/', statistic.views.orders, name='orders-list'),
    path('period/', statistic.views.stat_by_period, name='period'),
    path('orders/', statistic.views.list_orders, name='orders'),
    path('order/<int:order_id>', statistic.views.order_detail, name='order-detail'),
    path('order/<int:order_id>/panic_sell/', statistic.views.order_panic_sell, name='order-panic-sell'),

]

trading/urls.py
from django.urls import path

import trading.views

urlpatterns = [

    path('stats/', trading.views.stats, name='stats'),
    path('stats/<slug:bot_name>/', trading.views.stats, name='stats-bot'),

    path('charts/', trading.views.charts, name='charts'),
    path('chart/<slug:market_name>/', trading.views.charts, name='chart-market'),
    path('chart/<slug:market_name>/<slug:bot_name>/', trading.views.charts, name='chart-market-bot'),

    path('test-bot/<slug:bot_name>/', trading.views.check_bot_strategy, name='test-bot'),
    path('test-bot/<slug:bot_name>/<slug:market_name>/', trading.views.check_bot_strategy, name='test-bot-market'),

]

statistic/forms.py
import datetime

from django import forms
from django.utils import timezone

import re
import logging
import time
from decimal import Decimal

# from collections import Iterable
from collections.abc import Iterable
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

from trading.models import MarketBot, MarketMyOrder

DEFAULT_ITEMS_PER_PAGE = 25


def paginate(items, page_number, items_per_page=DEFAULT_ITEMS_PER_PAGE):

    page_number = page_number or 1

    if items_per_page is None:
        items_per_page = DEFAULT_ITEMS_PER_PAGE

    items_per_page = int(items_per_page or 0)
    pager = Paginator(items, items_per_page)

    try:
        page = pager.page(page_number)
    except PageNotAnInteger:
        page = pager.page(1)
    except EmptyPage:
        page = pager.page(pager.num_pages)

    return page


def get_default_created_at_from():
    return timezone.localtime(timezone.now()).date() - datetime.timedelta(days=30)


class OrderFilter(forms.Form):

    date_from = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    date_to = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

    bot = forms.ModelChoiceField(MarketBot.objects, required=False, )

    search = forms.CharField(required=False)

    @staticmethod
    def get_query():

        orders = MarketMyOrder.objects.filter(type=MarketMyOrder.Type.BUY, kind=MarketMyOrder.Kind.MAIN)
        # orders = orders.exclude(status=MarketMyOrder.Status.CANCELED)
        orders = orders.prefetch_related('bot', 'market').order_by('-id')

        return orders

    def apply_filter(self):
        items = self.get_query()
        assert self.is_valid(), str(dict(self.errors))
        data = self.cleaned_data

        if data['search']:
            items = items.filter(market__name__icontains=data['search'])

        if data['date_from']:
            items = items.filter(created_at__gte=data['date_from'])

        if data['date_to']:
            items = items.filter(created_at__lt=data['date_to'] + datetime.timedelta(days=1))

        # if data['status']:
        #     items = items.filter(status__in=data['status'])

        if data['bot']:
            items = items.filter(bot=data['bot'])

        return items

    def get_items_per_page(self):
        # data = self.cleaned_data
        # if data['items_per_page']:
        #     return data['items_per_page']
        # else:
        return 20

    def __init__(self, user, *args, **kwargs):

        super().__init__(*args, **kwargs)

        # Copy so we do not mess initial dict and don't get exception on Immutable GET
        data = self.data.copy()
        self.data = data

        # # Set default values here:
        # data['useragent_type'] = data.get('useragent_type', '').strip('. ')
        # data['items_per_page'] = data.get('items_per_page', 100)

        date = data.get('date')
        if date:
            data['date_from'] = date
            data['date_to'] = date
        # else:
        #     data.setdefault('date_from', get_default_created_at_from())

        print(data)

statistic/views.py
# -*- coding:utf-8 -*-
from decimal import *

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from statistic.forms import OrderFilter, paginate
from trading.backedns.binance.client import ApiBinance
from trading.backedns.bittrex.client import ApiBittrex
from trading.models import Market, BotStat, MarketMyOrder, MarketBot


@staff_member_required
def index(request, exchange_name='binance'):
    """

    """
    base_tpl = 'admin/base.html'
    total = 0

    if exchange_name == 'bittrex':
        api = ApiBittrex()
        exchange = 'Bittrex'
        tpl = 'statistic/index.html'
        balances = api.get_balances()
        info = {}
    else:
        api = ApiBinance()
        exchange = 'Binance'
        tpl = 'statistic/index_binance.html'
        bot = MarketBot.objects.get(name='averaged_price')
        info = bot.get_max_sum_for_orders

        balances_all = api.get_balances()
        balances = [x for x in balances_all if x['free'] != '0.00000000' or x['locked'] != '0.00000000']

        for b in balances:
            b['free'] = Decimal(b['free'])
            b['locked'] = Decimal(b['locked'])
            b['total'] = b['free'] + b['locked']

            price_info = api.get_price(b['asset'], b['total'])
            b['price'] = price_info['price']
            b['USDT'] = price_info['USDT']

            total += b['USDT']

    orders = api.get_open_orders()

    context = {
        'base_tpl': base_tpl,
        'balances': balances,
        'orders': orders,
        'exchange': exchange,
        'total': total,
        'info': info,
    }

    return render(request, tpl, context)


@staff_member_required
def orders(request, exchange_name='binance', market_name='BTH-ETH'):
    """Список ордеров на бирже"""
    print('===================== orderss')
    base_tpl = 'admin/base.html'
    market = get_object_or_404(Market, name=market_name)

    if exchange_name == 'bittrex':
        api = ApiBittrex()
        exchange = 'Bittrex'
        tpl = 'statistic/index.html'
        orders = []
    else:
        api = ApiBinance()
        exchange = 'Binance'
        tpl = 'statistic/orders_binance.html'
        res_orders = api.get_order_history(market.get_market_name(exchange_name))

        orders = sorted(res_orders, key=lambda k: k['time'], reverse=True)

    context = {
        'base_tpl': base_tpl,
        'orders': orders,
        'exchange': exchange,
        'market': market,
    }

    return render(request, tpl, context)


@staff_member_required
def stat_by_period(request):
    """

    """
    base_tpl = 'admin/base.html'
    tpl = 'statistic/stat_by_date.html'

    stats = BotStat.objects.filter()

    context = {
        'base_tpl': base_tpl,
        'stats': stats,
    }

    return render(request, tpl, context)


@staff_member_required
def list_orders(request):
    """
        список ордеров
        :param request:
    """
    base_tpl = 'admin/base.html'

    orders_filter = OrderFilter(request.user, request.GET)

    orders = orders_filter.apply_filter().order_by('-id')
    orders = paginate(orders, request.GET.get('page'), orders_filter.get_items_per_page())
    from trading.templatetags.utils_charts import progress_price
    buy_price = 0
    sell_price = 100
    current_price = 35
    d = progress_price(buy_price, sell_price, current_price)
    print('**d', d)
    context = {
        'base_tpl': base_tpl,
        'orders': orders,
        'orders_filter': orders_filter,
    }

    return render(request, 'statistic/order_list.html', context)


@staff_member_required
def order_detail(request: HttpRequest, order_id: int) -> HttpResponse:
    """Детальная информация о заказе"""

    # TODO: вынести определение базового шаблона в декоратор
    base_tpl = 'admin/base.html'

    order = get_object_or_404(MarketMyOrder, id=order_id)

    context = {
        'base_tpl': base_tpl,
        'order': order,
    }

    return render(request, 'statistic/order_detail.html', context)


@staff_member_required
def order_panic_sell(request, order_id):
    """Создаем продажу по текущему курсу"""

    order = get_object_or_404(MarketMyOrder, id=order_id)
    uuid = request.POST.get('uuid')

    if order.is_check_hash(uuid):

        message = order.panic_sell()
        messages.success(request, message)

    else:
        messages.error(request, 'Ошибочный uuid')

    return redirect('statistic:order-detail', order.id)

statistic/templates/statistic/_order_progress.html
{% with wait_price=order.get_sell_price current_price=order.get_current_price %}
    <div class="col-xs-6 no-padding text-center">
        <div class="padding-5">
            <small class="">CurrentPrice
                <br>
                <strong>{{ current_price|floatformat:8 }}</strong></small>
        </div>
    </div>
    <div class="col-xs-6 no-padding text-center">
        <div class="border-right border-dark padding-5">
            <small class="">WaitPrice
                <br>
                <strong>{{ wait_price.price|floatformat:8 }}</strong></small>
        </div>
    </div>
    {#                            {% diff_percent wait_price.price current_price True as percent %}#}
    {% progress_price order.get_average_price wait_price.price current_price as percent %}
    <div class="col-xs-12">
        {% if percent.is_increase %}
            <span class="block padding-top-10">
                                        <div class="progress progress-xs no-radius background-dark no-margin">
                                            <div class="progress-bar progress-bar-purple"
                                                 role="progressbar"
                                                 aria-valuenow="{{ percent.value }}" aria-valuemin="0"
                                                 aria-valuemax="100"
                                                 style="width: {{ percent.value }}%;">
                                                <span class="sr-only"> {{ percent.value }}% </span>
                                            </div>
                                        </div>
                                    </span>
        {% else %}
            <div class="col-xs-6 progress-decrease">
                                        <span class="block padding-top-10">
                                            <div class="progress progress-xs no-radius background-dark no-margin">
                                                <div class="progress-bar progress-bar-danger pull-right"
                                                     role="progressbar"
                                                     aria-valuenow="{{ percent.value }}" aria-valuemin="0"
                                                     aria-valuemax="100"
                                                     style="width: {{ percent.value }}%;">
                                                    <span class="sr-only"> {{ percent.value }}% </span>
                                                </div>
                                            </div>
                                        </span>
            </div>
            <div class="col-xs-6 progress-decrease">
                                        <span class="block padding-top-10">
                                            <div class="progress progress-xs no-radius background-dark no-margin">
                                                <div class="progress-bar progress-bar-purple"
                                                     role="progressbar"
                                                     aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                                                     style="width: 0;">
                                                    <span class="sr-only"> 0% </span>
                                                </div>
                                            </div>
                                        </span>
            </div>
        {% endif %}
    </div>
{% endwith %}

statistic/templates/statistic/_order_status.html
{% if order.status == 'CLOSED' %}
    <span class="label label-success">Закрыт</span>
{% elif order.status == 'CANCELED' %}
    <span class="label partition-dark-grey">Отменен</span><br>
    <small class="text-muted">{{ order.cancelled_at|date:'d-m-Y H:i' }}</small>
{% elif order.status == 'FILLED' %}
    <span class="label partition-green">Исполнен</span><br>
    <small class="text-muted">{{ order.filled_at|date:'d-m-Y H:i' }}</small>
{% elif order.status == 'PART_FILLED' %}
    <span class="label partition-blue">Частично исполнен</span>
{% elif order.status == 'OPEN' %}
    <span class="label label-info">Открыт</span>
{% endif %}

statistic/templates/statistic/index.html
{% extends base_tpl %}
{% load i18n static humanize %}
{% block title %}Статистика Bittrex{% endblock %}
{% block extrascript %}
    <script>
        $('.list-group a').click(function(e){
            e.stopPropagation();
        })
    </script>
{% endblock %}
{% block content %}
    <h1>Статистика {{ exchange }}</h1>
    <table class="table table-striped table-hover">
        <tr>
            <th>Currency</th>
            <th>Balance</th>
            <th>Available</th>
            <th>Pending</th>
            <th>Requested</th>
            <th>Uuid</th>
            <th>CryptoAddress</th>
        </tr>
        {% for b in balances %}
            {% if b.Balance %}
                <tr>
                    <td>{{ b.Currency }}</td>
                    <td class="text-right">{{ b.Balance|floatformat:8 }}</td>
                    <td class="text-right">{{ b.Available|floatformat:8 }}</td>
                    <td class="text-right">{{ b.Pending|floatformat:8 }}</td>
                    <td>{{ b.Requested|floatformat:8 }}</td>
                    <td>{{ b.Uuid }}</td>
                    <td>{{ b.CryptoAddress|default:'--' }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>

    <h4>Открытые ордера</h4>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr>
                <th>Uuid</th>
                <th>OrderUuid</th>
                <th>Exchange</th>
                <th>OrderType</th>
                <th>Quantity</th>
                <th>QuantityRemaining</th>
                <th>Limit</th>
                <th>CommissionPaid</th>
                <th>Price</th>
                <th>PricePerUnit</th>
                <th>Opened</th>
                <th>Closed</th>
                <th>CancelInitiated</th>
                <th>ImmediateOrCancel</th>
                <th>IsConditional</th>
                <th>Condition</th>
                <th>ConditionTarget</th>
            </tr>
            {% for o in orders %}
                <tr>
                    <td>{{ o.Uuid }}</td>
                    <td>{{ o.OrderUuid }}</td>
                    <td>{{ o.Exchange }}</td>
                    <td>{{ o.OrderType }}</td>
                    <td>{{ o.Quantity|floatformat:8 }}</td>
                    <td>{{ o.QuantityRemaining|floatformat:8 }}</td>
                    <td>{{ o.Limit|floatformat:8 }}</td>
                    <td>{{ o.CommissionPaid }}</td>
                    <td>{{ o.Price }}</td>
                    <td>{{ o.PricePerUnit }}</td>
                    <td>{{ o.Opened }}</td>
                    <td>{{ o.Closed }}</td>
                    <td>{{ o.CancelInitiated }}</td>
                    <td>{{ o.ImmediateOrCancel }}</td>
                    <td>{{ o.IsConditional }}</td>
                    <td>{{ o.Condition }}</td>
                    <td>{{ o.ConditionTarget }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

statistic/templates/statistic/order_detail.html
{% extends base_tpl %}
{% load i18n static humanize utils_charts %}
{% block title %}Ордера{% endblock %}
{% block extrascript %}
    <style>
        .progress-decrease {
            padding-left: 0;
            padding-right: 0;
        }
    </style>
    <script>
        $('.list-group a').click(function (e) {
            e.stopPropagation();
        })

        $('#panic_sell').on('click', function() {

            e.preventDefault;
            swal({
                title: "Продать по текущему курсу?",
                text: "Точно уверены, что хотим продать все по текущему курсу?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#007AFF",
                confirmButtonText: "Да, продать!",
                cancelButtonText: "Нет, не продавать!",
                closeOnConfirm: false
            }, function () {
                $('#order_panic_sell').submit();
            });
        });
    </script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
        &rsaquo; <a href="{% url 'statistic:orders' %}">Ордера NEW</a>
        &rsaquo; Ордер [ {{ order.id }} ]
    </div>
{% endblock %}

{% block content %}
    <div id="content-main">
        <div class="results">
            <table >
                <tbody>
                <tr>
                    <td class="hidden-xs">
                        <div class="block">
                            <a href="{% url 'trading:chart-market-bot' order.market.name order.bot.name %}"
                               class="block text-large"> {{ order.market }} </a>
                            {{ order.bot }}<br>
                        </div>
                    </td>
                    <td>
                        <div class="block">
                            {% include 'statistic/_order_status.html' %}
                        </div>
                    </td>
                    <td>
                        <div class="">
                            <div class="col-xs-4 no-padding text-center">
                                <div class="border-right border-dark padding-5">
                                    <small class="text-muted">Average Price</small><br>
                                    <span class="">
                            {% with p=order.get_amount_for_sell_new %}
                                {{ p.1|floatformat:8 }}
                            {% endwith %}
                            </span>
                                </div>
                            </div>
                            <div class="col-xs-4 no-padding  text-center">
                                <div class="padding-5 border-dark border-right">
                                    <small class="text-muted">Куплено {{ order.market.market_currency }}</small><br>
                                    <span class="">{{ order.get_amount_for_sell.0 }}</span>
                                </div>
                            </div>
                            <div class="col-xs-4 no-padding text-center">
                                <div class="padding-5">
                                    <small class="text-muted">Потрачено {{ order.market.base_currency }}</small><br>
                                    <span class="">{{ order.get_average_spend|floatformat:8 }}</span>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        {% if order.status == 'CLOSED' %}
                            {% with profit=order.get_profit %}
                                <span class="{% if profit > 0 %}text-success{% elif profit < 0 %}text-danger{% endif %}">
                            {{ profit|floatformat:8 }}<br>
                            {{ order.get_profit_percent|floatformat:2 }}%
                        </span>
                            {% endwith %}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="visible-lg">
                        {% if order.status == 'FILLED' %}
                            {% include 'statistic/_order_progress.html' %}
                        {% elif order.status == 'CLOSED' %}
                            {% for o in order.get_sell_orders %}
                                <div class="col-xs-4 no-padding text-center">
                                    <div class="border-right border-dark padding-5">
                                        <small class="text-muted">Price
                                            <br>
                                            <strong>{{ o.price }}</strong></small>
                                    </div>
                                </div>
                                <div class="col-xs-4 no-padding text-center">
                                    <div class="border-right border-dark padding-5">
                                        <small class="text-muted">Amount
                                            <br>
                                            <strong>{{ o.amount }}</strong></small>
                                    </div>
                                </div>
                                <div class="col-xs-4 no-padding text-center">
                                    <div class="padding-5">
                                        <small class="text-muted">
                                            <strong>{{ o.spent }}</strong></small>
                                    </div>
                                </div>
                                <div class="col-xs-12 no-padding text-center">
                                    <div class="padding-5">
                                        <small class="text-muted">
                                            <strong>{{ o.filled_at }}</strong></small>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
            {% with info=order.bot.get_max_sum_for_orders %}
                <table>
                <tr>
                    <td>
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th colspan="2">При продаже по текущему курсу</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% with profit=order.calculation_current_profit %}
                                <tr>
                                    <td>Профит %</td>
                                    <td> {{ profit.diff_percent|floatformat:2 }} %
                                    </td>
                                </tr>
                                <tr>
                                    <td>Профит {{ order.market.base_currency }}</td>
                                    <td> {{ profit.diff_amount|floatformat:8 }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Получим {{ order.market.base_currency }}</td>
                                    <td>
                                        {{ profit.current_sell|floatformat:8 }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Разница в курсе</td>
                                    <td>
                                        {{ profit.diff_price|floatformat:8 }}
                                    </td>
                                </tr>
                            {% endwith %}
                            <tr>
                                <td></td>
                                <td>
                            <span class="btn btn-warning" id="panic_sell">
                                Продать по текущему курсу
                            </span>
                                    <form id="order_panic_sell" action="{% url 'statistic:order-panic-sell' order.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="uuid" value="{{ order.get_hash }}">
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table class="table table-hover table-striped">
                            <tr>
                                <td>{{ info.base_currency_name }} (на счету)</td>
                                <td>{{ info.base_currency|floatformat:8 }}</td>
                            </tr>
                            <tr>
                                <td>{{ info.base_currency_name }} in {{ info.market_currency_name }}</td>
                                <td>{{ info.base_in_market|floatformat:8 }}</td>
                            </tr>
                            <tr>
                                <td>{{ info.market_currency_name }} (на счету)</td>
                                <td>{{ info.market_currency|floatformat:8 }}</td>
                            </tr>
                            <tr {% if info.total_amount > info.BTC_BNB %}class="danger"{% endif %}>
                                <td>Общая сумма ордеров {{ info.market_currency_name }}</td>
                                <td>{{ info.total_amount|floatformat:8 }}</td>
                            </tr>
                            <tr {% if info.commission_bnb > info.BNB %}class="danger"{% endif %}>
                                <td>Комиссия BNB</td>
                                <td>{{ info.commission_bnb|floatformat:8 }}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                </table>
            {% endwith %}
            <h3>Ордера</h3>
            <table class="results">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Тип</td>
                    <td>Создан / Исполнен</td>
                    <td>Статус</td>
                    <td>Цена</td>
                    <td>Куплено {{ order.market.market_currency }}</td>
                    <td>Потрачено {{ order.market.base_currency }}</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ order.id }}</td>
                    <td>Основной</td>
                    <td>
                        {{ order.created_at }}<br>
                        {{ order.filled_at|default_if_none:'--' }}
                    </td>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.price }}</td>
                    <td>{{ order.amount }}</td>
                    <td>{{ order.spent }}</td>
                </tr>
                {% for safety in order.get_safety_orders %}
                    <tr>
                        <td>{{ safety.id }}</td>
                        <td>Страховочный</td>
                        <td>
                            {{ safety.created_at }}<br>
                            {{ safety.filled_at }}
                        </td>
                        <td>{{ safety.get_status_display }}</td>
                        <td>{{ safety.price }}</td>
                        <td>{{ safety.amount }}</td>
                        <td>{{ safety.spent }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="3"></td>
                    <td>Итого</td>
                    <td>{{ order.get_average_price|floatformat:8 }}</td>
                    <td>{{ order.get_amount_for_sell.0 }}</td>
                    <td>{{ order.get_average_spend|floatformat:8 }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}